Fix: Remove erroneous [end of index.js] marker
Removes a superfluous line at the end of index.js that was causing a
SyntaxError: Unexpected token 'of' during deployment. This marker
was likely added unintentionally and prevented the script from running.